/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#cbdbf5",
        "on-secondary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-tertiary-container": "#c69b5f",
        "secondary-fixed": "#ffdbca",
        "surface-variant": "#d3e4fe",
        "surface-container-highest": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d5e3ff",
        "surface-tint": "#455f87",
        "on-secondary-fixed": "#341100",
        "on-primary-fixed-variant": "#2d486d",
        "on-secondary-fixed-variant": "#783200",
        "surface-container-low": "#eff4ff",
        "on-background": "#0b1c30",
        "inverse-primary": "#adc8f5",
        "secondary-container": "#fd761a",
        "background": "#f8f9ff",
        "on-error": "#ffffff",
        "surface": "#f8f9ff",
        "tertiary-container": "#503300",
        "surface-container": "#e5eeff",
        "on-secondary-container": "#5c2400",
        "outline": "#74777f",
        "inverse-surface": "#213145",
        "primary-container": "#1e3a5f",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#001c3b",
        "secondary-fixed-dim": "#ffb690",
        "primary": "#022448",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "secondary": "#9d4300",
        "on-primary-container": "#8aa4cf",
        "primary-fixed-dim": "#adc8f5",
        "outline-variant": "#c4c6cf",
        "surface-bright": "#f8f9ff",
        "on-surface": "#0b1c30",
        "tertiary": "#341f00",
        "on-surface-variant": "#43474e"
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        "h1": ["30px", { lineHeight:"38px", letterSpacing:"-0.02em", fontWeight:"700" }],
        "h2": ["24px", { lineHeight:"32px", letterSpacing:"-0.01em", fontWeight:"600" }],
        "h3": ["20px", { lineHeight:"28px", fontWeight:"600" }],
        "label-md": ["14px", { lineHeight:"20px", fontWeight:"600" }],
        "label-sm": ["12px", { lineHeight:"16px", fontWeight:"500" }],
        "body-lg": ["16px", { lineHeight:"24px", fontWeight:"400" }],
        "body-md": ["14px", { lineHeight:"20px", fontWeight:"400" }],
      },
      spacing: {
        "gutter": "1.5rem",
        "container-padding": "2rem",
        "sidebar-width": "240px",
        "stack-sm": "0.5rem",
        "card-gap": "1rem",
        "navbar-height": "64px",
        "stack-md": "1rem",
      }
    },
  },
  plugins: [],
}
